name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node and npm
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test

      - name: Build Application
        run: npm run build

  security-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          command: test
        continue-on-error: false 

  simulate-deploy:
    needs: [build-and-test, security-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Construir Imagen Docker
        run: docker build -t rotsu-app:test .

      - name: Simular Despliegue
        run: |
          # Levanta el contenedor
          docker run -d -p 3000:80 --name test-container rotsu-app:test
          
          # Espera 3 segundos para asegurar que Nginx inicie
          sleep 3
          
          # Hace un HTTP request. Si falla el comando 'exit 1' detiene el pipeline
          curl -f http://localhost:3000 || exit 1
          
          # Imprimir los logs del contenedor para que quede en el run
          docker logs test-container
          
          # Limpia y destruye el contenedor
          docker rm -f test-container
